version: '3.8'
services:
  postgresdb:
    container_name: skypiea_db
    image: postgres:16.8-alpine
    restart: always
    environment:
      - POSTGRES_USER=local_pg_user
      - POSTGRES_PASSWORD=local_pg_pass
    ports:
      - '5432:5432'
    volumes:
      - ./internal/storage/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ~/db/volume:/var/lib/postgresql/data


# reusable testable interface and methods
# bind to login
