apiVersion: v1
kind: Service
metadata:
  name: {{ include "skypiea-ai.fullname" . }}-server
  labels:
    {{- include "skypiea-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "skypiea-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
