{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "skypiea-ai.fullname" . }}-aws
spec:
  provider:
    aws:
      region: {{ .Values.externalSecrets.aws.region }}
      {{- if .Values.externalSecrets.aws.roleArn }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "skypiea-ai.serviceAccountName" . }}
            namespace: {{ .Release.Namespace }}
          serviceAccountAudience: sts.amazonaws.com
          role: {{ .Values.externalSecrets.aws.roleArn }}
      {{- else }}
      auth:
        secretRef:
          accessKeyID:
            name: {{ .Values.externalSecrets.aws.credentialsSecret }}
            key: access_key_id
          secretAccessKey:
            name: {{ .Values.externalSecrets.aws.credentialsSecret }}
            key: secret_access_key
      {{- end }}
{{- end }}
