{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.db_secret }}
  labels:
    {{- include "skypiea-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  secretStoreRef:
    name: {{ include "skypiea-ai.fullname" . }}-aws
    kind: ClusterSecretStore
  target:
    name: {{ .Values.db_secret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.database.dialect | lower }}_username
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName }}
        property: username
    - secretKey: {{ .Values.database.dialect | lower }}_password
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName }}
        property: password
{{- end }}
