# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ""
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  server:
    repository: "ghcr.io/fukaraca/skypiea-server"
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.0.8"
  worker:
    repository: "ghcr.io/fukaraca/skypiea-worker"
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.0.8"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
  # checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum | quote }}

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
  host: will.be.populated.by.workflow
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 400m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 120
  periodSeconds: 60
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 20
  timeoutSeconds: 5

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts:
 - name: config-volume
   mountPath: /app/skypiea-ai/configs
   readOnly: true


server:
  replicas: 1
  address: ""
  port: "8080"
  maxBodySizeMB: 25
  ginMode: "release" # test, release, debug
  sessionTimeout: 10m
  defaultRequestTimeout: 30s

worker:
  replicas: 0
  intervalTicker: 10s

log:
  level: "info"
  addSource: false

jwt:
  secret: "secret"
  domain: "localhost"

database:
  dialect: "postgres"
  postgresql:
    host: "127.0.0.1"
    port: "5432"
    database: "skypiea_ai"
    sslmode: "disable"
    timeout: "15s"

db_secret: "skypiea-ai-secret-db"

externalSecrets:
  enabled: false # --set externalSecrets.enabled=true for prod
  aws:
    region: us-west-2
    secretName: prod/rds/skypiea
    roleArn: ""
    credentialsSecret: ""

gemini:
  secret: "skypiea-ai-secret-gemini"
  clientConfig:
    backend: 1
    project: ""
    location: ""
  supportedModels:
    - "gemini-2.5-flash"
    - "gemini-2.5-flash-lite-preview-06-17"
    - "gemini-2.0-flash"
    - "gemini-2.0-flash-lite"
oauth2:
  google:
    secret: "skypiea-ai-secret-google-oauth"
    clientID: ""
    clientSecret: ""
    redirectURL: "https://chat.skypiea-ai.xyz/auth/google/callback"
    scopes:
      - "email"
      - "profile"