server:
  address: "127.0.0.1"
  port: "8080"
  maxBodySizeMB: 25
  ginMode: "debug" # test, release, debug
log:
  level: "debug"
  addSource: false
jwt:
  secret: "secret"
database:
  dialect: "postgresql"
  postgresql:
    host: "localhost"
    port: 5432
    username: "default_user"
    password: "default_pass"
    database: "default_db"
    sslmode: "disable"
  dynamodb:
    region: "us-west-2"
    endpoint: "http://localhost:8000"
    accessKeyId: "default-access-key"
    secretAccessKey: "default-secret-key"
