server:
  address: "127.0.0.1"
  port: "8080"
  maxBodySizeMB: 25
  ginMode: "debug" # test, release, debug
log:
  level: "debug"
  addSource: false
jwt:
  secret: "secret"
database:
  dialect: "postgresql"
  postgresql:
    host: "127.0.0.1"
    port: 5432
    username: "local_pg_user"
    password: "local_pg_pass"
    database: "skypiea_ai"
    sslmode: "disable"
