server:
  address: ""
  port: "8080"
  maxBodySizeMB: 25
  ginMode: "debug" # test, release, debug
  sessionTimeout: 10m
  defaultRequestTimeout: 30s
worker:
  intervalTicker: 10s
log:
  level: "info"
  addSource: false
jwt:
  secret: "secret"
  domain: "localhost"
database:
  dialect: "postgres"
  postgresql:
    host: "127.0.0.1"
    port: "5432"
    username: "local_pg_user"
    password: "local_pg_pass"
    database: "skypiea_ai"
    sslmode: "disable"
    timeout: "15s"
gemini:
  clientConfig:
    apiKey: ""
    backend: 1
    project: ""
    location: ""
  supportedModels:
    - "gemini-2.5-flash"
    - "gemini-2.5-flash-lite-preview-06-17"
    - "gemini-2.0-flash"
    - "gemini-2.0-flash-lite"
